import Head from 'next/head'
import Link from 'next/link'
import { useLayoutEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [pokemon, setPokemon] = useState([]);

  useLayoutEffect(() => {
    async function getPokemon() {
      const resp = await fetch('https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json')
      setPokemon(await resp.json())
    }
    getPokemon();
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon Next CSR App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.grid}>
          {pokemon?.map((pkm) => {
            return (
              <div className={styles.card} key={pkm.id}>
                <Link href={`/pokemon/${pkm.id}`}>
                  <a>
                    <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pkm.image}`}
                    />
                  </a>
                </Link>
                <h3>{pkm.name}</h3>
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}
